package com.openquartz.easyarchive.starter.security.model;

public enum PlatformCapabilityEnum {
    USER_CREATE_ARCHIVE_ADMIN,
    USER_CREATE_NORMAL_USER,
    USER_EDIT,
    USER_VIEW,
    DATASOURCE_CREATE,
    DATASOURCE_EDIT_AUTHORIZED,
    DATASOURCE_DISABLE_AUTHORIZED,
    DATASOURCE_TEST_AUTHORIZED,
    DATASOURCE_ASSIGN_MANAGE,
    DATASOURCE_ASSIGN_USE,
    ARCHIVE_GROUP_CREATE,
    ARCHIVE_GROUP_EDIT,
    ARCHIVE_GROUP_VIEW,
    ARCHIVE_GROUP_TRIGGER,
    ARCHIVE_GROUP_CANCEL,
    ARCHIVE_GROUP_DELETE,
    ARCHIVE_GROUP_STATUS_UPDATE,
    TASK_VIEW,
    TASK_LOG_VIEW,
    DASHBOARD_VIEW,
    NOTIFICATION_VIEW,
    OPERATION_LOG_VIEW
}
